services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${MEDIA_SERVER_PATH}/docker/jellyfin/config:/config
      - ${MEDIA_SERVER_PATH}/data/media/tv:/data/tv
      - ${MEDIA_SERVER_PATH}/data/media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    network_mode: bridge
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
    volumes:
      - ${MEDIA_SERVER_PATH}/docker/qb:/config
      - ${MEDIA_SERVER_PATH}/data/torrents:/data/torrents
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    # Other torrent manager
  # rtorrent:
  #   container_name: rtorrent
  #   image: crazymax/rtorrent-rutorrent:latest
  #   ports:
  #     - "8080:8080"
  #     - "6881:6881"
  #     - "8000:8000"
  #     - "9000:9000"
  #     - "50000:50000"
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=${TZ}
  #   volumes:
  #     - "${MEDIA_SERVER_PATH}/data/torrents:/data/torrents"
  #     - "${MEDIA_SERVER_PATH}/docker/rtorrent/data:/data"
  #     - "${MEDIA_SERVER_PATH}/docker/rtorrent/password:/passwd"
  #     - "${MEDIA_SERVER_PATH}/docker/rtorrent/temp:/tmp"
  #   restart: always
  #   network_mode: bridge

  ## Trackers
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${MEDIA_SERVER_PATH}/docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr: # TV
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${MEDIA_SERVER_PATH}/docker/sonarr:/config
      - ${MEDIA_SERVER_PATH}/data/media/tv:/data/tv
      - ${MEDIA_SERVER_PATH}/data/torrents:/data/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr: # Movies
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${MEDIA_SERVER_PATH}/docker/radarr:/config
      - ${MEDIA_SERVER_PATH}/data/media/movies:/data/movies
      - ${MEDIA_SERVER_PATH}/data/torrents:/data/torrents
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr: # Music
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${MEDIA_SERVER_PATH}/docker/lidarr:/config
      - ${MEDIA_SERVER_PATH}/data/media/music:/data/music
      - ${MEDIA_SERVER_PATH}/data/torrents:/data/torrents
    ports:
      - 8686:8686
    restart: unless-stopped
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    ports:
      - 5055:5055
    volumes:
      - ${MEDIA_SERVER_PATH}/docker/jellyseerr:/app/config
    restart: unless-stopped

  ## Homepage
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 80:3000
    volumes:
      - ${MEDIA_SERVER_PATH}/docker/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
